### ISSUE TITLE
API should not force users to redistribute pfl timers and other dependencies

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/orb-gmbal#14]
adding `ObjectRegistrationManager getObjectRegistrationManager() ;` method  to [ManagedObjectManager](https://github.com/eclipse-ee4j/orb-gmbal/blob/master/src/main/java/org/glassfish/gmbal/ManagedObjectManager.java) broke ability of clients to NOT redistribute gmbal project dependencies, such as those containing `org.glassfish.pfl.tf.timer.spi.ObjectRegistrationManager`, see also https://github.com/eclipse-ee4j/metro-jax-ws/issues/52

**Comment by russgold** [comment]
Do you mean the change that was made as part of:
```
commit e896923dc4a12f46a48de683580fc0f403540ed3
Author: Ken Cavanaugh <Ken.Cavanaugh@oracle.com>
Date:   Wed Apr 27 17:40:26 2011 -0700

    - Added missing code related to ObjectRegistrationManager.
```
?

And people are only running into this issue eight years later?

**Comment by lukasj** [comment]
That could be the cause.

I recall facing this problem with 4.0.0-b001 years ago but
a) at that time there was no need to change the dependency from org.glassfish.gmbal:gmbal-api-only:3.2.0-b003  to anything newer, so why to change what is not broken?
b) those who used to work on affected code apparently had other priorities and vast majority of them already moved away to other projects; not saying that the project itself changed ownership few times during past ~7 years as well

**Comment by russgold** [comment]
I haven't seen any gmbal-api-only build in all the years I've been working on these projects. I suspect it vanished when Ken changed the build from ant to maven. 

If you can help me to understand the issue, maybe we can come up with a solution. Why is it a problem for clients to distribute pfl-timer? Who uses getObjectRegistrationManager() ?

**Comment by lukasj** [comment]
[LazyMOMProvider](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/api/server/LazyMOMProvider.java) has some description of the functionality.

It all starts in [WSEndpointImpl](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/server/WSEndpointImpl.java#L583), eventually may get to sth like [RewritingMOM](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/server/MonitorBase.java#L345) or [WSEndpointMOMProxy.java](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/server/WSEndpointMOMProxy.java). 

All this is extended in/used by https://github.com/eclipse-ee4j/metro-wsit project through [WSEndpointCollectionBasedMOMListener](https://github.com/eclipse-ee4j/metro-wsit/blob/master/wsit/metro-commons/src/main/java/com/sun/xml/ws/commons/WSEndpointCollectionBasedMOMListener.java)

**Comment by russgold** [comment]
Sorry, I don't understand what you're saying. Which of my questions are you answering?

**Comment by lukasj** [comment]
> If you can help me to understand the issue

[LazyMOMProvider](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/api/server/LazyMOMProvider.java)  has some documentation in class level javadoc about how gmbal integration is supposed to work in jaxws and metro projects. In general, jaxws is supposed to be lightweight and should use api-only, metro, which is built on top of jaxws, delivers the implementation.

> Who uses getObjectRegistrationManager() ?

Don't know. I can see reference to 'org.glassfish.external.amx.AMXGlassfish.DEFAULT' - no idea who is it.

For the jaxws I managed to lower the number of dependencies to have pfl-basic and pfl-tf on classpaths, which seems to be enough for existing tests to pass without annoying warnings. The thing is, that when I look at OSGi headers in these artifacts, it is evident that also at least pfl-dynamic and pfl-asm are required.
